# My default Fuchsia environment setup sans secrets.
set -x CIPD_PARALLEL_DOWNLOADS 32
set -x NINJA_STATUS_MAX_COMMANDS 8
set -x NINJA_STATUS_REFRESH_MILLIS 250
set -x NINJA_PERSISTENT_MODE 1
set -x FUCHSIA_ANALYTICS_DISABLED 1
set -x FX_BUILD_WITH_LABELS 1
set -x FX_BUILD_RBE_STATS 1
set -x FX_RA_EXPERIMENTS_ENABLED 1
